### ISSUE TITLE
User manual?

### ISSUE THREAD

**Issue by cszhe** [buty4649/osc-fish-complete#1]
I installed it but don't know how to use it. Any hints?

**Comment by buty4649** [comment]
Sorry, this is a development version and will not work.
However, I'm making the necessary modifications to make it work and it will be working soon.

**Comment by buty4649** [comment]
@cszhe hi, I updated to v0.1.0, please try it.
[README](https://github.com/buty4649/osc-fish-complete/blob/master/README.md) has also been updated, please refer to it.
